openapi: 3.1.0
info:
  title: vfc-api
  version: 0.1.0-SNAPSHOT
  summary: Virtual Financial Coach API
  description: |-
    APIs VFC1 needs to deliver credit data upon request. 
    Data will be provided by TransUnion.
  contact:
    name: API Team at eGain
    email: APITeam@eGain.com
    url: 'https://www.eGain.com/dev-central/'
  termsOfService: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  license:
    name: Apache 2.0
    identifier: APSL-2.0
servers:
  - url: 'http://vfc.eGain.com:3000'
paths:
  'consumer/{consumer-identifier}/get-rating':
    parameters:
      - schema:
          type: string
        name: consumer-identifier
        in: path
        required: true
    get:
      summary: get credit rating for one consumer
      tags: []
      responses:
        '200':
          description: Credit data found for consumer
          content:
            application/json:
              schema:
                $ref: ../models/credit-rating.yaml
        '401':
          description: Unauthorized
        '404':
          description: Consumer rating not retrieved
        '408':
          description: Request Timeout
      operationId: get-consumer-credit-rating
      description: |-
        Retrieve credit report of consumer by consumer identifier. 
        "consumer identifier" can be one of: (a few different forms)
      parameters:
        - schema:
            type: string
            enum:
              - consumer-id
              - name-and-address
              - name-and-ssn
          in: query
          name: consumer-identifier
components:
  schemas:
    consumer-name:
      $ref: ../models/consumer-name.yaml
    credit-report:
      $ref: ../models/credit-report.yaml
